// Code generated by go-swagger; DO NOT EDIT.

package sdb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// SdbOpenReader is a Reader for the SdbOpen structure.
type SdbOpenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SdbOpenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSdbOpenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSdbOpenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSdbOpenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSdbOpenOK creates a SdbOpenOK with default headers values
func NewSdbOpenOK() *SdbOpenOK {
	return &SdbOpenOK{}
}

/* SdbOpenOK describes a response with status code 200, with default header values.

Successful Stop
*/
type SdbOpenOK struct {
	Payload *models.Success
}

func (o *SdbOpenOK) Error() string {
	return fmt.Sprintf("[POST /sdb/open][%d] sdbOpenOK  %+v", 200, o.Payload)
}
func (o *SdbOpenOK) GetPayload() *models.Success {
	return o.Payload
}

func (o *SdbOpenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSdbOpenBadRequest creates a SdbOpenBadRequest with default headers values
func NewSdbOpenBadRequest() *SdbOpenBadRequest {
	return &SdbOpenBadRequest{}
}

/* SdbOpenBadRequest describes a response with status code 400, with default header values.

Error
*/
type SdbOpenBadRequest struct {
	Payload *models.Error
}

func (o *SdbOpenBadRequest) Error() string {
	return fmt.Sprintf("[POST /sdb/open][%d] sdbOpenBadRequest  %+v", 400, o.Payload)
}
func (o *SdbOpenBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SdbOpenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSdbOpenInternalServerError creates a SdbOpenInternalServerError with default headers values
func NewSdbOpenInternalServerError() *SdbOpenInternalServerError {
	return &SdbOpenInternalServerError{}
}

/* SdbOpenInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type SdbOpenInternalServerError struct {
	Payload *models.ServerError
}

func (o *SdbOpenInternalServerError) Error() string {
	return fmt.Sprintf("[POST /sdb/open][%d] sdbOpenInternalServerError  %+v", 500, o.Payload)
}
func (o *SdbOpenInternalServerError) GetPayload() *models.ServerError {
	return o.Payload
}

func (o *SdbOpenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
