// Code generated by go-swagger; DO NOT EDIT.

package sdb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// SdbCloseReader is a Reader for the SdbClose structure.
type SdbCloseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SdbCloseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSdbCloseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSdbCloseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSdbCloseInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSdbCloseOK creates a SdbCloseOK with default headers values
func NewSdbCloseOK() *SdbCloseOK {
	return &SdbCloseOK{}
}

/* SdbCloseOK describes a response with status code 200, with default header values.

Successful Close
*/
type SdbCloseOK struct {
	Payload *models.Success
}

func (o *SdbCloseOK) Error() string {
	return fmt.Sprintf("[POST /sdb/close][%d] sdbCloseOK  %+v", 200, o.Payload)
}
func (o *SdbCloseOK) GetPayload() *models.Success {
	return o.Payload
}

func (o *SdbCloseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSdbCloseBadRequest creates a SdbCloseBadRequest with default headers values
func NewSdbCloseBadRequest() *SdbCloseBadRequest {
	return &SdbCloseBadRequest{}
}

/* SdbCloseBadRequest describes a response with status code 400, with default header values.

Error
*/
type SdbCloseBadRequest struct {
	Payload *models.Error
}

func (o *SdbCloseBadRequest) Error() string {
	return fmt.Sprintf("[POST /sdb/close][%d] sdbCloseBadRequest  %+v", 400, o.Payload)
}
func (o *SdbCloseBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SdbCloseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSdbCloseInternalServerError creates a SdbCloseInternalServerError with default headers values
func NewSdbCloseInternalServerError() *SdbCloseInternalServerError {
	return &SdbCloseInternalServerError{}
}

/* SdbCloseInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type SdbCloseInternalServerError struct {
	Payload *models.ServerError
}

func (o *SdbCloseInternalServerError) Error() string {
	return fmt.Sprintf("[POST /sdb/close][%d] sdbCloseInternalServerError  %+v", 500, o.Payload)
}
func (o *SdbCloseInternalServerError) GetPayload() *models.ServerError {
	return o.Payload
}

func (o *SdbCloseInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
