// Code generated by go-swagger; DO NOT EDIT.

package sdb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// NewSdbOpenParams creates a new SdbOpenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSdbOpenParams() *SdbOpenParams {
	return &SdbOpenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSdbOpenParamsWithTimeout creates a new SdbOpenParams object
// with the ability to set a timeout on a request.
func NewSdbOpenParamsWithTimeout(timeout time.Duration) *SdbOpenParams {
	return &SdbOpenParams{
		timeout: timeout,
	}
}

// NewSdbOpenParamsWithContext creates a new SdbOpenParams object
// with the ability to set a context for a request.
func NewSdbOpenParamsWithContext(ctx context.Context) *SdbOpenParams {
	return &SdbOpenParams{
		Context: ctx,
	}
}

// NewSdbOpenParamsWithHTTPClient creates a new SdbOpenParams object
// with the ability to set a custom HTTPClient for a request.
func NewSdbOpenParamsWithHTTPClient(client *http.Client) *SdbOpenParams {
	return &SdbOpenParams{
		HTTPClient: client,
	}
}

/* SdbOpenParams contains all the parameters to send to the API endpoint
   for the sdb open operation.

   Typically these are written to a http.Request.
*/
type SdbOpenParams struct {

	/* Open.

	   Registeration Payload
	*/
	Open models.Shutter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the sdb open params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SdbOpenParams) WithDefaults() *SdbOpenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the sdb open params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SdbOpenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the sdb open params
func (o *SdbOpenParams) WithTimeout(timeout time.Duration) *SdbOpenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sdb open params
func (o *SdbOpenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sdb open params
func (o *SdbOpenParams) WithContext(ctx context.Context) *SdbOpenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sdb open params
func (o *SdbOpenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sdb open params
func (o *SdbOpenParams) WithHTTPClient(client *http.Client) *SdbOpenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sdb open params
func (o *SdbOpenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOpen adds the open to the sdb open params
func (o *SdbOpenParams) WithOpen(open models.Shutter) *SdbOpenParams {
	o.SetOpen(open)
	return o
}

// SetOpen adds the open to the sdb open params
func (o *SdbOpenParams) SetOpen(open models.Shutter) {
	o.Open = open
}

// WriteToRequest writes these params to a swagger request
func (o *SdbOpenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Open != nil {
		if err := r.SetBodyParam(o.Open); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
