// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"shutter/restapi/operations/chambre"
	"shutter/restapi/operations/salon"
	"shutter/restapi/operations/sdb"
	"shutter/restapi/operations/user"
)

// NewShutterAPI creates a new Shutter instance
func NewShutterAPI(spec *loads.Document) *ShutterAPI {
	return &ShutterAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		ChambreChambreCloseHandler: chambre.ChambreCloseHandlerFunc(func(params chambre.ChambreCloseParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation chambre.ChambreClose has not yet been implemented")
		}),
		ChambreChambreOpenHandler: chambre.ChambreOpenHandlerFunc(func(params chambre.ChambreOpenParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation chambre.ChambreOpen has not yet been implemented")
		}),
		ChambreChambreStopHandler: chambre.ChambreStopHandlerFunc(func(params chambre.ChambreStopParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation chambre.ChambreStop has not yet been implemented")
		}),
		UserLoginHandler: user.LoginHandlerFunc(func(params user.LoginParams) middleware.Responder {
			return middleware.NotImplemented("operation user.Login has not yet been implemented")
		}),
		UserRegisterHandler: user.RegisterHandlerFunc(func(params user.RegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation user.Register has not yet been implemented")
		}),
		SalonSalonCloseHandler: salon.SalonCloseHandlerFunc(func(params salon.SalonCloseParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation salon.SalonClose has not yet been implemented")
		}),
		SalonSalonOpenHandler: salon.SalonOpenHandlerFunc(func(params salon.SalonOpenParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation salon.SalonOpen has not yet been implemented")
		}),
		SalonSalonStopHandler: salon.SalonStopHandlerFunc(func(params salon.SalonStopParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation salon.SalonStop has not yet been implemented")
		}),
		SdbSdbCloseHandler: sdb.SdbCloseHandlerFunc(func(params sdb.SdbCloseParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation sdb.SdbClose has not yet been implemented")
		}),
		SdbSdbOpenHandler: sdb.SdbOpenHandlerFunc(func(params sdb.SdbOpenParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation sdb.SdbOpen has not yet been implemented")
		}),
		SdbSdbStopHandler: sdb.SdbStopHandlerFunc(func(params sdb.SdbStopParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation sdb.SdbStop has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (Bearer) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*ShutterAPI the shutter API */
type ShutterAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BearerAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// ChambreChambreCloseHandler sets the operation handler for the chambre close operation
	ChambreChambreCloseHandler chambre.ChambreCloseHandler
	// ChambreChambreOpenHandler sets the operation handler for the chambre open operation
	ChambreChambreOpenHandler chambre.ChambreOpenHandler
	// ChambreChambreStopHandler sets the operation handler for the chambre stop operation
	ChambreChambreStopHandler chambre.ChambreStopHandler
	// UserLoginHandler sets the operation handler for the login operation
	UserLoginHandler user.LoginHandler
	// UserRegisterHandler sets the operation handler for the register operation
	UserRegisterHandler user.RegisterHandler
	// SalonSalonCloseHandler sets the operation handler for the salon close operation
	SalonSalonCloseHandler salon.SalonCloseHandler
	// SalonSalonOpenHandler sets the operation handler for the salon open operation
	SalonSalonOpenHandler salon.SalonOpenHandler
	// SalonSalonStopHandler sets the operation handler for the salon stop operation
	SalonSalonStopHandler salon.SalonStopHandler
	// SdbSdbCloseHandler sets the operation handler for the sdb close operation
	SdbSdbCloseHandler sdb.SdbCloseHandler
	// SdbSdbOpenHandler sets the operation handler for the sdb open operation
	SdbSdbOpenHandler sdb.SdbOpenHandler
	// SdbSdbStopHandler sets the operation handler for the sdb stop operation
	SdbSdbStopHandler sdb.SdbStopHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *ShutterAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *ShutterAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *ShutterAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ShutterAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *ShutterAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *ShutterAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ShutterAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ShutterAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ShutterAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ShutterAPI
func (o *ShutterAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.ChambreChambreCloseHandler == nil {
		unregistered = append(unregistered, "chambre.ChambreCloseHandler")
	}
	if o.ChambreChambreOpenHandler == nil {
		unregistered = append(unregistered, "chambre.ChambreOpenHandler")
	}
	if o.ChambreChambreStopHandler == nil {
		unregistered = append(unregistered, "chambre.ChambreStopHandler")
	}
	if o.UserLoginHandler == nil {
		unregistered = append(unregistered, "user.LoginHandler")
	}
	if o.UserRegisterHandler == nil {
		unregistered = append(unregistered, "user.RegisterHandler")
	}
	if o.SalonSalonCloseHandler == nil {
		unregistered = append(unregistered, "salon.SalonCloseHandler")
	}
	if o.SalonSalonOpenHandler == nil {
		unregistered = append(unregistered, "salon.SalonOpenHandler")
	}
	if o.SalonSalonStopHandler == nil {
		unregistered = append(unregistered, "salon.SalonStopHandler")
	}
	if o.SdbSdbCloseHandler == nil {
		unregistered = append(unregistered, "sdb.SdbCloseHandler")
	}
	if o.SdbSdbOpenHandler == nil {
		unregistered = append(unregistered, "sdb.SdbOpenHandler")
	}
	if o.SdbSdbStopHandler == nil {
		unregistered = append(unregistered, "sdb.SdbStopHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ShutterAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ShutterAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "Bearer":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.BearerAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *ShutterAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *ShutterAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *ShutterAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ShutterAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the shutter API
func (o *ShutterAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *ShutterAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/chambre/close"] = chambre.NewChambreClose(o.context, o.ChambreChambreCloseHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/chambre/open"] = chambre.NewChambreOpen(o.context, o.ChambreChambreOpenHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/chambre/stop"] = chambre.NewChambreStop(o.context, o.ChambreChambreStopHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = user.NewLogin(o.context, o.UserLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/register"] = user.NewRegister(o.context, o.UserRegisterHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/salon/close"] = salon.NewSalonClose(o.context, o.SalonSalonCloseHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/salon/open"] = salon.NewSalonOpen(o.context, o.SalonSalonOpenHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/salon/stop"] = salon.NewSalonStop(o.context, o.SalonSalonStopHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/sdb/close"] = sdb.NewSdbClose(o.context, o.SdbSdbCloseHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/sdb/open"] = sdb.NewSdbOpen(o.context, o.SdbSdbOpenHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/sdb/stop"] = sdb.NewSdbStop(o.context, o.SdbSdbStopHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ShutterAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *ShutterAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *ShutterAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *ShutterAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *ShutterAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
