// Code generated by go-swagger; DO NOT EDIT.

// Package restapi shutter
//
//  Schemes:
//    http
//  Host: 0.0.0.0:8081
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
