// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"shutter/models"
)

// ChambreStopOKCode is the HTTP code returned for type ChambreStopOK
const ChambreStopOKCode int = 200

/*ChambreStopOK Successful Stop

swagger:response chambreStopOK
*/
type ChambreStopOK struct {

	/*
	  In: Body
	*/
	Payload *models.Success `json:"body,omitempty"`
}

// NewChambreStopOK creates ChambreStopOK with default headers values
func NewChambreStopOK() *ChambreStopOK {

	return &ChambreStopOK{}
}

// WithPayload adds the payload to the chambre stop o k response
func (o *ChambreStopOK) WithPayload(payload *models.Success) *ChambreStopOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chambre stop o k response
func (o *ChambreStopOK) SetPayload(payload *models.Success) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChambreStopOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChambreStopBadRequestCode is the HTTP code returned for type ChambreStopBadRequest
const ChambreStopBadRequestCode int = 400

/*ChambreStopBadRequest Error

swagger:response chambreStopBadRequest
*/
type ChambreStopBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewChambreStopBadRequest creates ChambreStopBadRequest with default headers values
func NewChambreStopBadRequest() *ChambreStopBadRequest {

	return &ChambreStopBadRequest{}
}

// WithPayload adds the payload to the chambre stop bad request response
func (o *ChambreStopBadRequest) WithPayload(payload *models.Error) *ChambreStopBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chambre stop bad request response
func (o *ChambreStopBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChambreStopBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChambreStopInternalServerErrorCode is the HTTP code returned for type ChambreStopInternalServerError
const ChambreStopInternalServerErrorCode int = 500

/*ChambreStopInternalServerError Server error

swagger:response chambreStopInternalServerError
*/
type ChambreStopInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewChambreStopInternalServerError creates ChambreStopInternalServerError with default headers values
func NewChambreStopInternalServerError() *ChambreStopInternalServerError {

	return &ChambreStopInternalServerError{}
}

// WithPayload adds the payload to the chambre stop internal server error response
func (o *ChambreStopInternalServerError) WithPayload(payload *models.ServerError) *ChambreStopInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chambre stop internal server error response
func (o *ChambreStopInternalServerError) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChambreStopInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
