// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ChambreOpenHandlerFunc turns a function with the right signature into a chambre open handler
type ChambreOpenHandlerFunc func(ChambreOpenParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ChambreOpenHandlerFunc) Handle(params ChambreOpenParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ChambreOpenHandler interface for that can handle valid chambre open params
type ChambreOpenHandler interface {
	Handle(ChambreOpenParams, interface{}) middleware.Responder
}

// NewChambreOpen creates a new http.Handler for the chambre open operation
func NewChambreOpen(ctx *middleware.Context, handler ChambreOpenHandler) *ChambreOpen {
	return &ChambreOpen{Context: ctx, Handler: handler}
}

/* ChambreOpen swagger:route POST /chambre/open Chambre chambreOpen

Open chambre shutter

Open chambre shutter

*/
type ChambreOpen struct {
	Context *middleware.Context
	Handler ChambreOpenHandler
}

func (o *ChambreOpen) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewChambreOpenParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
