// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ChambreStopHandlerFunc turns a function with the right signature into a chambre stop handler
type ChambreStopHandlerFunc func(ChambreStopParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ChambreStopHandlerFunc) Handle(params ChambreStopParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ChambreStopHandler interface for that can handle valid chambre stop params
type ChambreStopHandler interface {
	Handle(ChambreStopParams, interface{}) middleware.Responder
}

// NewChambreStop creates a new http.Handler for the chambre stop operation
func NewChambreStop(ctx *middleware.Context, handler ChambreStopHandler) *ChambreStop {
	return &ChambreStop{Context: ctx, Handler: handler}
}

/* ChambreStop swagger:route POST /chambre/stop Chambre chambreStop

Stop chambre shutter

Stop chambre shutter

*/
type ChambreStop struct {
	Context *middleware.Context
	Handler ChambreStopHandler
}

func (o *ChambreStop) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewChambreStopParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
