// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ChambreCloseHandlerFunc turns a function with the right signature into a chambre close handler
type ChambreCloseHandlerFunc func(ChambreCloseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ChambreCloseHandlerFunc) Handle(params ChambreCloseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ChambreCloseHandler interface for that can handle valid chambre close params
type ChambreCloseHandler interface {
	Handle(ChambreCloseParams, interface{}) middleware.Responder
}

// NewChambreClose creates a new http.Handler for the chambre close operation
func NewChambreClose(ctx *middleware.Context, handler ChambreCloseHandler) *ChambreClose {
	return &ChambreClose{Context: ctx, Handler: handler}
}

/* ChambreClose swagger:route POST /chambre/close Chambre chambreClose

Close chambre shutter

Close chambre shutter

*/
type ChambreClose struct {
	Context *middleware.Context
	Handler ChambreCloseHandler
}

func (o *ChambreClose) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewChambreCloseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
