// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// NewChambreOpenParams creates a new ChambreOpenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChambreOpenParams() *ChambreOpenParams {
	return &ChambreOpenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChambreOpenParamsWithTimeout creates a new ChambreOpenParams object
// with the ability to set a timeout on a request.
func NewChambreOpenParamsWithTimeout(timeout time.Duration) *ChambreOpenParams {
	return &ChambreOpenParams{
		timeout: timeout,
	}
}

// NewChambreOpenParamsWithContext creates a new ChambreOpenParams object
// with the ability to set a context for a request.
func NewChambreOpenParamsWithContext(ctx context.Context) *ChambreOpenParams {
	return &ChambreOpenParams{
		Context: ctx,
	}
}

// NewChambreOpenParamsWithHTTPClient creates a new ChambreOpenParams object
// with the ability to set a custom HTTPClient for a request.
func NewChambreOpenParamsWithHTTPClient(client *http.Client) *ChambreOpenParams {
	return &ChambreOpenParams{
		HTTPClient: client,
	}
}

/* ChambreOpenParams contains all the parameters to send to the API endpoint
   for the chambre open operation.

   Typically these are written to a http.Request.
*/
type ChambreOpenParams struct {

	/* Open.

	   Registeration Payload
	*/
	Open models.Shutter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the chambre open params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChambreOpenParams) WithDefaults() *ChambreOpenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the chambre open params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChambreOpenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the chambre open params
func (o *ChambreOpenParams) WithTimeout(timeout time.Duration) *ChambreOpenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the chambre open params
func (o *ChambreOpenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the chambre open params
func (o *ChambreOpenParams) WithContext(ctx context.Context) *ChambreOpenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the chambre open params
func (o *ChambreOpenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the chambre open params
func (o *ChambreOpenParams) WithHTTPClient(client *http.Client) *ChambreOpenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the chambre open params
func (o *ChambreOpenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOpen adds the open to the chambre open params
func (o *ChambreOpenParams) WithOpen(open models.Shutter) *ChambreOpenParams {
	o.SetOpen(open)
	return o
}

// SetOpen adds the open to the chambre open params
func (o *ChambreOpenParams) SetOpen(open models.Shutter) {
	o.Open = open
}

// WriteToRequest writes these params to a swagger request
func (o *ChambreOpenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Open != nil {
		if err := r.SetBodyParam(o.Open); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
