// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new chambre API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for chambre API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ChambreClose(params *ChambreCloseParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChambreCloseOK, error)

	ChambreOpen(params *ChambreOpenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChambreOpenOK, error)

	ChambreStop(params *ChambreStopParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChambreStopOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ChambreClose closes chambre shutter

  Close chambre shutter
*/
func (a *Client) ChambreClose(params *ChambreCloseParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChambreCloseOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChambreCloseParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Chambre/close",
		Method:             "POST",
		PathPattern:        "/chambre/close",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ChambreCloseReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChambreCloseOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Chambre/close: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ChambreOpen opens chambre shutter

  Open chambre shutter
*/
func (a *Client) ChambreOpen(params *ChambreOpenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChambreOpenOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChambreOpenParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Chambre/open",
		Method:             "POST",
		PathPattern:        "/chambre/open",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ChambreOpenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChambreOpenOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Chambre/open: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ChambreStop stops chambre shutter

  Stop chambre shutter
*/
func (a *Client) ChambreStop(params *ChambreStopParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ChambreStopOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChambreStopParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Chambre/stop",
		Method:             "POST",
		PathPattern:        "/chambre/stop",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ChambreStopReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChambreStopOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Chambre/stop: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
