// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// NewChambreStopParams creates a new ChambreStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChambreStopParams() *ChambreStopParams {
	return &ChambreStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChambreStopParamsWithTimeout creates a new ChambreStopParams object
// with the ability to set a timeout on a request.
func NewChambreStopParamsWithTimeout(timeout time.Duration) *ChambreStopParams {
	return &ChambreStopParams{
		timeout: timeout,
	}
}

// NewChambreStopParamsWithContext creates a new ChambreStopParams object
// with the ability to set a context for a request.
func NewChambreStopParamsWithContext(ctx context.Context) *ChambreStopParams {
	return &ChambreStopParams{
		Context: ctx,
	}
}

// NewChambreStopParamsWithHTTPClient creates a new ChambreStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewChambreStopParamsWithHTTPClient(client *http.Client) *ChambreStopParams {
	return &ChambreStopParams{
		HTTPClient: client,
	}
}

/* ChambreStopParams contains all the parameters to send to the API endpoint
   for the chambre stop operation.

   Typically these are written to a http.Request.
*/
type ChambreStopParams struct {

	/* Stop.

	   Registeration Payload
	*/
	Stop models.Shutter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the chambre stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChambreStopParams) WithDefaults() *ChambreStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the chambre stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChambreStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the chambre stop params
func (o *ChambreStopParams) WithTimeout(timeout time.Duration) *ChambreStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the chambre stop params
func (o *ChambreStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the chambre stop params
func (o *ChambreStopParams) WithContext(ctx context.Context) *ChambreStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the chambre stop params
func (o *ChambreStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the chambre stop params
func (o *ChambreStopParams) WithHTTPClient(client *http.Client) *ChambreStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the chambre stop params
func (o *ChambreStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStop adds the stop to the chambre stop params
func (o *ChambreStopParams) WithStop(stop models.Shutter) *ChambreStopParams {
	o.SetStop(stop)
	return o
}

// SetStop adds the stop to the chambre stop params
func (o *ChambreStopParams) SetStop(stop models.Shutter) {
	o.Stop = stop
}

// WriteToRequest writes these params to a swagger request
func (o *ChambreStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Stop != nil {
		if err := r.SetBodyParam(o.Stop); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
