// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// NewChambreCloseParams creates a new ChambreCloseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChambreCloseParams() *ChambreCloseParams {
	return &ChambreCloseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChambreCloseParamsWithTimeout creates a new ChambreCloseParams object
// with the ability to set a timeout on a request.
func NewChambreCloseParamsWithTimeout(timeout time.Duration) *ChambreCloseParams {
	return &ChambreCloseParams{
		timeout: timeout,
	}
}

// NewChambreCloseParamsWithContext creates a new ChambreCloseParams object
// with the ability to set a context for a request.
func NewChambreCloseParamsWithContext(ctx context.Context) *ChambreCloseParams {
	return &ChambreCloseParams{
		Context: ctx,
	}
}

// NewChambreCloseParamsWithHTTPClient creates a new ChambreCloseParams object
// with the ability to set a custom HTTPClient for a request.
func NewChambreCloseParamsWithHTTPClient(client *http.Client) *ChambreCloseParams {
	return &ChambreCloseParams{
		HTTPClient: client,
	}
}

/* ChambreCloseParams contains all the parameters to send to the API endpoint
   for the chambre close operation.

   Typically these are written to a http.Request.
*/
type ChambreCloseParams struct {

	/* Close.

	   Registeration Payload
	*/
	Close models.Shutter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the chambre close params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChambreCloseParams) WithDefaults() *ChambreCloseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the chambre close params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChambreCloseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the chambre close params
func (o *ChambreCloseParams) WithTimeout(timeout time.Duration) *ChambreCloseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the chambre close params
func (o *ChambreCloseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the chambre close params
func (o *ChambreCloseParams) WithContext(ctx context.Context) *ChambreCloseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the chambre close params
func (o *ChambreCloseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the chambre close params
func (o *ChambreCloseParams) WithHTTPClient(client *http.Client) *ChambreCloseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the chambre close params
func (o *ChambreCloseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClose adds the close to the chambre close params
func (o *ChambreCloseParams) WithClose(close models.Shutter) *ChambreCloseParams {
	o.SetClose(close)
	return o
}

// SetClose adds the close to the chambre close params
func (o *ChambreCloseParams) SetClose(close models.Shutter) {
	o.Close = close
}

// WriteToRequest writes these params to a swagger request
func (o *ChambreCloseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Close != nil {
		if err := r.SetBodyParam(o.Close); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
