// Code generated by go-swagger; DO NOT EDIT.

package chambre

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// ChambreStopReader is a Reader for the ChambreStop structure.
type ChambreStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChambreStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewChambreStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewChambreStopBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewChambreStopInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewChambreStopOK creates a ChambreStopOK with default headers values
func NewChambreStopOK() *ChambreStopOK {
	return &ChambreStopOK{}
}

/* ChambreStopOK describes a response with status code 200, with default header values.

Successful Stop
*/
type ChambreStopOK struct {
	Payload *models.Success
}

func (o *ChambreStopOK) Error() string {
	return fmt.Sprintf("[POST /chambre/stop][%d] chambreStopOK  %+v", 200, o.Payload)
}
func (o *ChambreStopOK) GetPayload() *models.Success {
	return o.Payload
}

func (o *ChambreStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChambreStopBadRequest creates a ChambreStopBadRequest with default headers values
func NewChambreStopBadRequest() *ChambreStopBadRequest {
	return &ChambreStopBadRequest{}
}

/* ChambreStopBadRequest describes a response with status code 400, with default header values.

Error
*/
type ChambreStopBadRequest struct {
	Payload *models.Error
}

func (o *ChambreStopBadRequest) Error() string {
	return fmt.Sprintf("[POST /chambre/stop][%d] chambreStopBadRequest  %+v", 400, o.Payload)
}
func (o *ChambreStopBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ChambreStopBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChambreStopInternalServerError creates a ChambreStopInternalServerError with default headers values
func NewChambreStopInternalServerError() *ChambreStopInternalServerError {
	return &ChambreStopInternalServerError{}
}

/* ChambreStopInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ChambreStopInternalServerError struct {
	Payload *models.ServerError
}

func (o *ChambreStopInternalServerError) Error() string {
	return fmt.Sprintf("[POST /chambre/stop][%d] chambreStopInternalServerError  %+v", 500, o.Payload)
}
func (o *ChambreStopInternalServerError) GetPayload() *models.ServerError {
	return o.Payload
}

func (o *ChambreStopInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
