// Code generated by go-swagger; DO NOT EDIT.

package sdb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SdbStopHandlerFunc turns a function with the right signature into a sdb stop handler
type SdbStopHandlerFunc func(SdbStopParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SdbStopHandlerFunc) Handle(params SdbStopParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SdbStopHandler interface for that can handle valid sdb stop params
type SdbStopHandler interface {
	Handle(SdbStopParams, interface{}) middleware.Responder
}

// NewSdbStop creates a new http.Handler for the sdb stop operation
func NewSdbStop(ctx *middleware.Context, handler SdbStopHandler) *SdbStop {
	return &SdbStop{Context: ctx, Handler: handler}
}

/* SdbStop swagger:route POST /sdb/stop Sdb sdbStop

Stop sdb shutter

Stop sdb shutter

*/
type SdbStop struct {
	Context *middleware.Context
	Handler SdbStopHandler
}

func (o *SdbStop) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSdbStopParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
