// Code generated by go-swagger; DO NOT EDIT.

package sdb

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SdbCloseHandlerFunc turns a function with the right signature into a sdb close handler
type SdbCloseHandlerFunc func(SdbCloseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SdbCloseHandlerFunc) Handle(params SdbCloseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SdbCloseHandler interface for that can handle valid sdb close params
type SdbCloseHandler interface {
	Handle(SdbCloseParams, interface{}) middleware.Responder
}

// NewSdbClose creates a new http.Handler for the sdb close operation
func NewSdbClose(ctx *middleware.Context, handler SdbCloseHandler) *SdbClose {
	return &SdbClose{Context: ctx, Handler: handler}
}

/* SdbClose swagger:route POST /sdb/close Sdb sdbClose

Close sdb shutter

Close sdb shutter

*/
type SdbClose struct {
	Context *middleware.Context
	Handler SdbCloseHandler
}

func (o *SdbClose) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSdbCloseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
