// Code generated by go-swagger; DO NOT EDIT.

package salon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SalonOpenHandlerFunc turns a function with the right signature into a salon open handler
type SalonOpenHandlerFunc func(SalonOpenParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SalonOpenHandlerFunc) Handle(params SalonOpenParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SalonOpenHandler interface for that can handle valid salon open params
type SalonOpenHandler interface {
	Handle(SalonOpenParams, interface{}) middleware.Responder
}

// NewSalonOpen creates a new http.Handler for the salon open operation
func NewSalonOpen(ctx *middleware.Context, handler SalonOpenHandler) *SalonOpen {
	return &SalonOpen{Context: ctx, Handler: handler}
}

/* SalonOpen swagger:route POST /salon/open Salon salonOpen

Open salon shutter

Open salon shutter

*/
type SalonOpen struct {
	Context *middleware.Context
	Handler SalonOpenHandler
}

func (o *SalonOpen) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSalonOpenParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
