// Code generated by go-swagger; DO NOT EDIT.

package salon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SalonStopHandlerFunc turns a function with the right signature into a salon stop handler
type SalonStopHandlerFunc func(SalonStopParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SalonStopHandlerFunc) Handle(params SalonStopParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SalonStopHandler interface for that can handle valid salon stop params
type SalonStopHandler interface {
	Handle(SalonStopParams, interface{}) middleware.Responder
}

// NewSalonStop creates a new http.Handler for the salon stop operation
func NewSalonStop(ctx *middleware.Context, handler SalonStopHandler) *SalonStop {
	return &SalonStop{Context: ctx, Handler: handler}
}

/* SalonStop swagger:route POST /salon/stop Salon salonStop

Stop salon shutter

Stop salon shutter

*/
type SalonStop struct {
	Context *middleware.Context
	Handler SalonStopHandler
}

func (o *SalonStop) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSalonStopParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
