// Code generated by go-swagger; DO NOT EDIT.

package salon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"shutter/models"
)

// SalonOpenOKCode is the HTTP code returned for type SalonOpenOK
const SalonOpenOKCode int = 200

/*SalonOpenOK Successful Open

swagger:response salonOpenOK
*/
type SalonOpenOK struct {

	/*
	  In: Body
	*/
	Payload *models.Success `json:"body,omitempty"`
}

// NewSalonOpenOK creates SalonOpenOK with default headers values
func NewSalonOpenOK() *SalonOpenOK {

	return &SalonOpenOK{}
}

// WithPayload adds the payload to the salon open o k response
func (o *SalonOpenOK) WithPayload(payload *models.Success) *SalonOpenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the salon open o k response
func (o *SalonOpenOK) SetPayload(payload *models.Success) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SalonOpenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SalonOpenBadRequestCode is the HTTP code returned for type SalonOpenBadRequest
const SalonOpenBadRequestCode int = 400

/*SalonOpenBadRequest Error

swagger:response salonOpenBadRequest
*/
type SalonOpenBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSalonOpenBadRequest creates SalonOpenBadRequest with default headers values
func NewSalonOpenBadRequest() *SalonOpenBadRequest {

	return &SalonOpenBadRequest{}
}

// WithPayload adds the payload to the salon open bad request response
func (o *SalonOpenBadRequest) WithPayload(payload *models.Error) *SalonOpenBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the salon open bad request response
func (o *SalonOpenBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SalonOpenBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SalonOpenInternalServerErrorCode is the HTTP code returned for type SalonOpenInternalServerError
const SalonOpenInternalServerErrorCode int = 500

/*SalonOpenInternalServerError Server error

swagger:response salonOpenInternalServerError
*/
type SalonOpenInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewSalonOpenInternalServerError creates SalonOpenInternalServerError with default headers values
func NewSalonOpenInternalServerError() *SalonOpenInternalServerError {

	return &SalonOpenInternalServerError{}
}

// WithPayload adds the payload to the salon open internal server error response
func (o *SalonOpenInternalServerError) WithPayload(payload *models.ServerError) *SalonOpenInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the salon open internal server error response
func (o *SalonOpenInternalServerError) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SalonOpenInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
