// Code generated by entc, DO NOT EDIT.

package users

import (
	"time"
)

const (
	// Label holds the string label denoting the users type in the database.
	Label = "users"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPseudo holds the string denoting the pseudo field in the database.
	FieldPseudo = "pseudo"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldFname holds the string denoting the fname field in the database.
	FieldFname = "fname"
	// FieldLname holds the string denoting the lname field in the database.
	FieldLname = "lname"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the users in the database.
	Table = "users"
)

// Columns holds all SQL columns for users fields.
var Columns = []string{
	FieldID,
	FieldPseudo,
	FieldPassword,
	FieldFname,
	FieldLname,
	FieldEmail,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PseudoValidator is a validator for the "pseudo" field. It is called by the builders before save.
	PseudoValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// FnameValidator is a validator for the "fname" field. It is called by the builders before save.
	FnameValidator func(string) error
	// LnameValidator is a validator for the "lname" field. It is called by the builders before save.
	LnameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
