// Code generated by go-swagger; DO NOT EDIT.

package salon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// SalonStopReader is a Reader for the SalonStop structure.
type SalonStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SalonStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSalonStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSalonStopBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSalonStopInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSalonStopOK creates a SalonStopOK with default headers values
func NewSalonStopOK() *SalonStopOK {
	return &SalonStopOK{}
}

/* SalonStopOK describes a response with status code 200, with default header values.

Successful Stop
*/
type SalonStopOK struct {
	Payload *models.Success
}

func (o *SalonStopOK) Error() string {
	return fmt.Sprintf("[POST /salon/stop][%d] salonStopOK  %+v", 200, o.Payload)
}
func (o *SalonStopOK) GetPayload() *models.Success {
	return o.Payload
}

func (o *SalonStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Success)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSalonStopBadRequest creates a SalonStopBadRequest with default headers values
func NewSalonStopBadRequest() *SalonStopBadRequest {
	return &SalonStopBadRequest{}
}

/* SalonStopBadRequest describes a response with status code 400, with default header values.

Error
*/
type SalonStopBadRequest struct {
	Payload *models.Error
}

func (o *SalonStopBadRequest) Error() string {
	return fmt.Sprintf("[POST /salon/stop][%d] salonStopBadRequest  %+v", 400, o.Payload)
}
func (o *SalonStopBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SalonStopBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSalonStopInternalServerError creates a SalonStopInternalServerError with default headers values
func NewSalonStopInternalServerError() *SalonStopInternalServerError {
	return &SalonStopInternalServerError{}
}

/* SalonStopInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type SalonStopInternalServerError struct {
	Payload *models.ServerError
}

func (o *SalonStopInternalServerError) Error() string {
	return fmt.Sprintf("[POST /salon/stop][%d] salonStopInternalServerError  %+v", 500, o.Payload)
}
func (o *SalonStopInternalServerError) GetPayload() *models.ServerError {
	return o.Payload
}

func (o *SalonStopInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
