// Code generated by go-swagger; DO NOT EDIT.

package salon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// NewSalonStopParams creates a new SalonStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSalonStopParams() *SalonStopParams {
	return &SalonStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSalonStopParamsWithTimeout creates a new SalonStopParams object
// with the ability to set a timeout on a request.
func NewSalonStopParamsWithTimeout(timeout time.Duration) *SalonStopParams {
	return &SalonStopParams{
		timeout: timeout,
	}
}

// NewSalonStopParamsWithContext creates a new SalonStopParams object
// with the ability to set a context for a request.
func NewSalonStopParamsWithContext(ctx context.Context) *SalonStopParams {
	return &SalonStopParams{
		Context: ctx,
	}
}

// NewSalonStopParamsWithHTTPClient creates a new SalonStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewSalonStopParamsWithHTTPClient(client *http.Client) *SalonStopParams {
	return &SalonStopParams{
		HTTPClient: client,
	}
}

/* SalonStopParams contains all the parameters to send to the API endpoint
   for the salon stop operation.

   Typically these are written to a http.Request.
*/
type SalonStopParams struct {

	/* Stop.

	   Registeration Payload
	*/
	Stop models.Shutter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the salon stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SalonStopParams) WithDefaults() *SalonStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the salon stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SalonStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the salon stop params
func (o *SalonStopParams) WithTimeout(timeout time.Duration) *SalonStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the salon stop params
func (o *SalonStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the salon stop params
func (o *SalonStopParams) WithContext(ctx context.Context) *SalonStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the salon stop params
func (o *SalonStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the salon stop params
func (o *SalonStopParams) WithHTTPClient(client *http.Client) *SalonStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the salon stop params
func (o *SalonStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStop adds the stop to the salon stop params
func (o *SalonStopParams) WithStop(stop models.Shutter) *SalonStopParams {
	o.SetStop(stop)
	return o
}

// SetStop adds the stop to the salon stop params
func (o *SalonStopParams) SetStop(stop models.Shutter) {
	o.Stop = stop
}

// WriteToRequest writes these params to a swagger request
func (o *SalonStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Stop != nil {
		if err := r.SetBodyParam(o.Stop); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
