// Code generated by go-swagger; DO NOT EDIT.

package salon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"shutter/models"
)

// NewSalonCloseParams creates a new SalonCloseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSalonCloseParams() *SalonCloseParams {
	return &SalonCloseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSalonCloseParamsWithTimeout creates a new SalonCloseParams object
// with the ability to set a timeout on a request.
func NewSalonCloseParamsWithTimeout(timeout time.Duration) *SalonCloseParams {
	return &SalonCloseParams{
		timeout: timeout,
	}
}

// NewSalonCloseParamsWithContext creates a new SalonCloseParams object
// with the ability to set a context for a request.
func NewSalonCloseParamsWithContext(ctx context.Context) *SalonCloseParams {
	return &SalonCloseParams{
		Context: ctx,
	}
}

// NewSalonCloseParamsWithHTTPClient creates a new SalonCloseParams object
// with the ability to set a custom HTTPClient for a request.
func NewSalonCloseParamsWithHTTPClient(client *http.Client) *SalonCloseParams {
	return &SalonCloseParams{
		HTTPClient: client,
	}
}

/* SalonCloseParams contains all the parameters to send to the API endpoint
   for the salon close operation.

   Typically these are written to a http.Request.
*/
type SalonCloseParams struct {

	/* Close.

	   Registeration Payload
	*/
	Close models.Shutter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the salon close params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SalonCloseParams) WithDefaults() *SalonCloseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the salon close params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SalonCloseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the salon close params
func (o *SalonCloseParams) WithTimeout(timeout time.Duration) *SalonCloseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the salon close params
func (o *SalonCloseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the salon close params
func (o *SalonCloseParams) WithContext(ctx context.Context) *SalonCloseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the salon close params
func (o *SalonCloseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the salon close params
func (o *SalonCloseParams) WithHTTPClient(client *http.Client) *SalonCloseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the salon close params
func (o *SalonCloseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClose adds the close to the salon close params
func (o *SalonCloseParams) WithClose(close models.Shutter) *SalonCloseParams {
	o.SetClose(close)
	return o
}

// SetClose adds the close to the salon close params
func (o *SalonCloseParams) SetClose(close models.Shutter) {
	o.Close = close
}

// WriteToRequest writes these params to a swagger request
func (o *SalonCloseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Close != nil {
		if err := r.SetBodyParam(o.Close); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
